# Generated by Django 3.1.3 on 2020-11-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('about', models.TextField(max_length=2048)),
                ('max_categories', models.IntegerField(default=20)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
