# Generated by Django 3.1.3 on 2020-11-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='max_categories',
            new_name='max_products',
        ),
    ]
